// data.js — Seed recipe database (public library)
const RECIPES = [
  {
    id: 'r001',
    title: 'Spaghetti Carbonara',
    description: 'Classic Roman pasta with eggs, pecorino, guanciale and black pepper. Silky sauce, no cream needed.',
    category: 'pasta',
    coverEmoji: '🍝',
    tags: ['italian', 'quick', 'classic'],
    servings: 2,
    prepTime: 10,
    cookTime: 20,
    ingredients: [
      { name: 'spaghetti', quantity: 200, unit: 'g' },
      { name: 'eggs', quantity: 3, unit: 'whole' },
      { name: 'pecorino romano', quantity: 60, unit: 'g' },
      { name: 'guanciale', quantity: 100, unit: 'g' },
      { name: 'black pepper', quantity: 1, unit: 'tsp' },
      { name: 'salt', quantity: 1, unit: 'tsp' },
    ],
    steps: [
      'Bring a large pot of heavily salted water to a boil.',
      'Cook spaghetti according to package instructions until al dente. Reserve 1 cup of pasta water.',
      'Slice guanciale into small cubes and fry in a dry pan over medium heat until crispy and rendered.',
      'Whisk together eggs, grated pecorino and plenty of black pepper in a bowl.',
      'Drain pasta and immediately add to the guanciale pan off the heat.',
      'Pour egg mixture over pasta, tossing vigorously and adding pasta water a splash at a time until silky.',
    ],
  },
  {
    id: 'r002',
    title: 'Chicken Tikka Masala',
    description: 'Creamy, vibrant tomato curry with tender marinated grilled chicken. A crowd-pleasing classic.',
    category: 'curry',
    coverEmoji: '🍛',
    tags: ['indian', 'spicy', 'comfort'],
    servings: 4,
    prepTime: 20,
    cookTime: 35,
    ingredients: [
      { name: 'chicken breast', quantity: 600, unit: 'g' },
      { name: 'yogurt', quantity: 150, unit: 'ml' },
      { name: 'tomato passata', quantity: 400, unit: 'ml' },
      { name: 'heavy cream', quantity: 100, unit: 'ml' },
      { name: 'onion', quantity: 1, unit: 'whole' },
      { name: 'garlic', quantity: 4, unit: 'cloves' },
      { name: 'ginger', quantity: 1, unit: 'tsp' },
      { name: 'garam masala', quantity: 2, unit: 'tsp' },
      { name: 'cumin', quantity: 1, unit: 'tsp' },
      { name: 'turmeric', quantity: 0.5, unit: 'tsp' },
      { name: 'olive oil', quantity: 2, unit: 'tbsp' },
      { name: 'salt', quantity: 1, unit: 'tsp' },
    ],
    steps: [
      'Marinate chicken in yogurt, half the garlic, ginger, 1 tsp garam masala and salt for at least 30 minutes.',
      'Grill or pan-fry marinated chicken until charred. Set aside.',
      'Sauté diced onion in olive oil until golden. Add remaining garlic and cook 1 minute.',
      'Add cumin, turmeric, remaining garam masala. Stir 30 seconds.',
      'Pour in passata, simmer 15 minutes. Stir in cream and grilled chicken.',
      'Simmer 5 more minutes. Serve with naan or basmati rice.',
    ],
  },
  {
    id: 'r003',
    title: 'Caesar Salad',
    description: 'Crisp romaine with a bold homemade Caesar dressing, parmesan shards and golden croutons.',
    category: 'salad',
    coverEmoji: '🥗',
    tags: ['american', 'quick', 'cold', 'vegetarian'],
    servings: 2,
    prepTime: 15,
    cookTime: 5,
    ingredients: [
      { name: 'romaine lettuce', quantity: 1, unit: 'head' },
      { name: 'parmesan', quantity: 50, unit: 'g' },
      { name: 'bread', quantity: 2, unit: 'slices' },
      { name: 'eggs', quantity: 1, unit: 'whole' },
      { name: 'lemon juice', quantity: 2, unit: 'tbsp' },
      { name: 'worcestershire sauce', quantity: 1, unit: 'tsp' },
      { name: 'garlic', quantity: 2, unit: 'cloves' },
      { name: 'olive oil', quantity: 3, unit: 'tbsp' },
      { name: 'dijon mustard', quantity: 1, unit: 'tsp' },
      { name: 'salt', quantity: 0.5, unit: 'tsp' },
      { name: 'black pepper', quantity: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Cube bread and toast in 1 tbsp olive oil in a pan until golden. Season with salt.',
      'Whisk together egg yolk, lemon juice, mustard, worcestershire, minced garlic.',
      'Drizzle in remaining olive oil while whisking to emulsify into a creamy dressing.',
      'Chop romaine into rough pieces. Toss with dressing and most of the parmesan.',
      'Top with croutons and remaining parmesan shavings. Season with black pepper.',
    ],
  },
  {
    id: 'r004',
    title: 'French Onion Soup',
    description: 'Slow-caramelized onions in rich beef broth, topped with a gruyere-laden baguette toast.',
    category: 'soup',
    coverEmoji: '🧅',
    tags: ['french', 'comfort', 'slow-cook'],
    servings: 4,
    prepTime: 15,
    cookTime: 60,
    ingredients: [
      { name: 'onions', quantity: 1, unit: 'kg' },
      { name: 'beef stock', quantity: 1, unit: 'L' },
      { name: 'dry white wine', quantity: 150, unit: 'ml' },
      { name: 'gruyere', quantity: 120, unit: 'g' },
      { name: 'baguette', quantity: 4, unit: 'slices' },
      { name: 'butter', quantity: 40, unit: 'g' },
      { name: 'thyme', quantity: 3, unit: 'sprigs' },
      { name: 'bay leaf', quantity: 1, unit: 'whole' },
      { name: 'salt', quantity: 1, unit: 'tsp' },
      { name: 'black pepper', quantity: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Thinly slice all onions. Melt butter in a heavy pot over medium-low heat.',
      'Add onions and a pinch of salt. Cook 45 minutes, stirring regularly, until deeply golden.',
      'Deglaze with white wine, scraping up any fond. Add thyme sprigs and bay leaf.',
      'Pour in beef stock, season with pepper. Simmer 15 minutes.',
      'Ladle soup into oven-safe bowls. Float a baguette slice on top, pile with grated gruyere.',
      'Broil until cheese is bubbling and browned. Serve immediately.',
    ],
  },
  {
    id: 'r005',
    title: 'Avocado Toast',
    description: 'Smashed avocado on crispy sourdough with chilli flakes, lemon and sea salt. Breakfast perfection.',
    category: 'breakfast',
    coverEmoji: '🥑',
    tags: ['quick', 'vegetarian', 'healthy'],
    servings: 1,
    prepTime: 5,
    cookTime: 5,
    ingredients: [
      { name: 'sourdough bread', quantity: 2, unit: 'slices' },
      { name: 'avocado', quantity: 1, unit: 'whole' },
      { name: 'lemon juice', quantity: 1, unit: 'tbsp' },
      { name: 'chilli flakes', quantity: 0.5, unit: 'tsp' },
      { name: 'salt', quantity: 0.5, unit: 'tsp' },
      { name: 'olive oil', quantity: 1, unit: 'tbsp' },
    ],
    steps: [
      'Toast the sourdough slices until golden and crispy.',
      'Halve the avocado, remove the stone, and scoop the flesh into a bowl.',
      'Mash with lemon juice and salt. Taste and adjust seasoning.',
      'Spread generously on toast, drizzle with olive oil, top with chilli flakes.',
    ],
  },
  {
    id: 'r006',
    title: 'Beef Tacos',
    description: 'Smoky seasoned ground beef in warm corn tortillas with cheddar, sour cream and fresh lime.',
    category: 'mains',
    coverEmoji: '🌮',
    tags: ['mexican', 'quick', 'crowd-pleaser'],
    servings: 4,
    prepTime: 10,
    cookTime: 15,
    ingredients: [
      { name: 'ground beef', quantity: 400, unit: 'g' },
      { name: 'corn tortillas', quantity: 8, unit: 'whole' },
      { name: 'onion', quantity: 1, unit: 'whole' },
      { name: 'garlic', quantity: 2, unit: 'cloves' },
      { name: 'cumin', quantity: 1.5, unit: 'tsp' },
      { name: 'chilli powder', quantity: 1, unit: 'tsp' },
      { name: 'cheddar cheese', quantity: 80, unit: 'g' },
      { name: 'sour cream', quantity: 100, unit: 'ml' },
      { name: 'lime', quantity: 1, unit: 'whole' },
      { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      { name: 'salt', quantity: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Dice onion and mince garlic. Sauté in olive oil over medium-high heat until soft.',
      'Add ground beef, breaking it up. Cook until browned throughout.',
      'Season with cumin, chilli powder and salt. Stir well and cook 2 more minutes.',
      'Warm tortillas in a dry pan or directly over a gas flame.',
      'Fill tortillas with beef mixture, shredded cheddar, sour cream and a squeeze of lime.',
    ],
  },
  {
    id: 'r007',
    title: 'Chocolate Chip Cookies',
    description: 'Chewy in the centre, crisp at the edges — the perfect chocolate chip cookie every time.',
    category: 'dessert',
    coverEmoji: '🍪',
    tags: ['baking', 'sweet', 'american', 'classic'],
    servings: 24,
    prepTime: 15,
    cookTime: 12,
    ingredients: [
      { name: 'all-purpose flour', quantity: 280, unit: 'g' },
      { name: 'butter', quantity: 225, unit: 'g' },
      { name: 'brown sugar', quantity: 200, unit: 'g' },
      { name: 'white sugar', quantity: 100, unit: 'g' },
      { name: 'eggs', quantity: 2, unit: 'whole' },
      { name: 'vanilla extract', quantity: 2, unit: 'tsp' },
      { name: 'baking soda', quantity: 1, unit: 'tsp' },
      { name: 'salt', quantity: 1, unit: 'tsp' },
      { name: 'chocolate chips', quantity: 340, unit: 'g' },
    ],
    steps: [
      'Preheat oven to 190°C (375°F). Line baking sheets with parchment.',
      'Beat softened butter with both sugars until light and fluffy, about 3 minutes.',
      'Beat in eggs one at a time, then vanilla extract.',
      'Whisk together flour, baking soda and salt. Gradually mix into wet ingredients.',
      'Fold in chocolate chips. Scoop rounded tablespoons onto prepared baking sheets.',
      'Bake 10–12 minutes until edges are golden. Cool on sheet 5 minutes before transferring.',
    ],
  },
  {
    id: 'r008',
    title: 'Shakshuka',
    description: 'Eggs poached in a fragrant spiced tomato and pepper sauce. Serve straight from the pan with bread.',
    category: 'breakfast',
    coverEmoji: '🍳',
    tags: ['middle-eastern', 'vegetarian', 'spicy'],
    servings: 2,
    prepTime: 10,
    cookTime: 25,
    ingredients: [
      { name: 'canned tomatoes', quantity: 400, unit: 'g' },
      { name: 'eggs', quantity: 4, unit: 'whole' },
      { name: 'onion', quantity: 1, unit: 'whole' },
      { name: 'red bell pepper', quantity: 1, unit: 'whole' },
      { name: 'garlic', quantity: 3, unit: 'cloves' },
      { name: 'cumin', quantity: 1, unit: 'tsp' },
      { name: 'paprika', quantity: 1, unit: 'tsp' },
      { name: 'chilli flakes', quantity: 0.5, unit: 'tsp' },
      { name: 'olive oil', quantity: 2, unit: 'tbsp' },
      { name: 'feta cheese', quantity: 60, unit: 'g' },
      { name: 'salt', quantity: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Heat olive oil in a wide frying pan. Sauté diced onion and pepper until softened, ~8 minutes.',
      'Add minced garlic, cumin, paprika and chilli flakes. Stir and cook 1 minute.',
      'Pour in canned tomatoes, crushing them. Season with salt. Simmer 10 minutes.',
      'Make 4 wells in the sauce and crack an egg into each.',
      'Cover and cook on low heat until whites are set but yolks still runny, ~6 minutes.',
      'Scatter crumbled feta over the top. Serve with crusty bread.',
    ],
  },
  {
    id: 'r009',
    title: 'Lemon Garlic Roast Chicken',
    description: 'A whole chicken roasted with lemon, garlic, butter and fresh herbs. Sunday lunch perfection.',
    category: 'mains',
    coverEmoji: '🍗',
    tags: ['classic', 'sunday-roast', 'slow-cook'],
    servings: 4,
    prepTime: 20,
    cookTime: 90,
    ingredients: [
      { name: 'whole chicken', quantity: 1.5, unit: 'kg' },
      { name: 'lemon', quantity: 2, unit: 'whole' },
      { name: 'garlic', quantity: 6, unit: 'cloves' },
      { name: 'butter', quantity: 50, unit: 'g' },
      { name: 'thyme', quantity: 5, unit: 'sprigs' },
      { name: 'rosemary', quantity: 2, unit: 'sprigs' },
      { name: 'olive oil', quantity: 2, unit: 'tbsp' },
      { name: 'salt', quantity: 1, unit: 'tsp' },
      { name: 'black pepper', quantity: 1, unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 200°C (400°F). Pat chicken dry with paper towels.',
      'Mix softened butter with zest of 1 lemon, 2 minced garlic cloves, salt and pepper.',
      'Loosen skin over breast and rub butter mixture under and over the skin.',
      'Stuff cavity with quartered lemons, remaining garlic, thyme and rosemary.',
      'Drizzle olive oil over chicken and place in roasting tin, breast-side up.',
      'Roast 1h30 or until juices run clear. Rest 15 minutes before carving.',
    ],
  },
  {
    id: 'r010',
    title: 'Veggie Stir-Fry',
    description: 'Fast wok-tossed vegetables in a soy-ginger sauce over fluffy jasmine rice. Weeknight hero.',
    category: 'mains',
    coverEmoji: '🥦',
    tags: ['asian', 'vegan', 'quick', 'healthy'],
    servings: 2,
    prepTime: 15,
    cookTime: 10,
    ingredients: [
      { name: 'broccoli', quantity: 200, unit: 'g' },
      { name: 'snap peas', quantity: 100, unit: 'g' },
      { name: 'carrot', quantity: 1, unit: 'whole' },
      { name: 'soy sauce', quantity: 3, unit: 'tbsp' },
      { name: 'sesame oil', quantity: 1, unit: 'tbsp' },
      { name: 'ginger', quantity: 1, unit: 'tsp' },
      { name: 'garlic', quantity: 2, unit: 'cloves' },
      { name: 'jasmine rice', quantity: 200, unit: 'g' },
      { name: 'cornstarch', quantity: 1, unit: 'tbsp' },
    ],
    steps: [
      'Cook jasmine rice according to package instructions.',
      'Mix soy sauce, sesame oil, cornstarch and a splash of water into a sauce.',
      'Heat a wok or large pan on high heat. Add a splash of oil.',
      'Stir-fry broccoli, snap peas, sliced carrot, garlic and ginger for 5–6 minutes until tender-crisp.',
      'Pour sauce over vegetables and toss until glossy and well-coated.',
      'Serve immediately over rice.',
    ],
  },
  {
    id: 'r011',
    title: 'Banana Pancakes',
    description: 'Fluffy golden pancakes with mashed ripe banana, perfect with maple syrup and fresh berries.',
    category: 'breakfast',
    coverEmoji: '🥞',
    tags: ['sweet', 'quick', 'vegetarian', 'kid-friendly'],
    servings: 2,
    prepTime: 10,
    cookTime: 15,
    ingredients: [
      { name: 'all-purpose flour', quantity: 150, unit: 'g' },
      { name: 'banana', quantity: 2, unit: 'whole' },
      { name: 'eggs', quantity: 2, unit: 'whole' },
      { name: 'milk', quantity: 180, unit: 'ml' },
      { name: 'baking powder', quantity: 2, unit: 'tsp' },
      { name: 'butter', quantity: 30, unit: 'g' },
      { name: 'maple syrup', quantity: 4, unit: 'tbsp' },
      { name: 'salt', quantity: 0.25, unit: 'tsp' },
    ],
    steps: [
      'Mash bananas thoroughly in a large bowl.',
      'Beat in eggs and milk until combined.',
      'Stir in flour, baking powder and salt until just smooth (a few lumps are fine).',
      'Melt butter in a non-stick pan over medium heat.',
      'Pour small ladlefuls of batter, cook 2–3 minutes per side until golden.',
      'Serve in a stack drizzled with maple syrup.',
    ],
  },
  {
    id: 'r012',
    title: 'Tomato Basil Bruschetta',
    description: 'Grilled sourdough loaded with fresh tomato, basil, garlic and best-quality extra-virgin olive oil.',
    category: 'snack',
    coverEmoji: '🍅',
    tags: ['italian', 'vegetarian', 'quick', 'appetizer'],
    servings: 4,
    prepTime: 10,
    cookTime: 5,
    ingredients: [
      { name: 'sourdough bread', quantity: 4, unit: 'slices' },
      { name: 'tomatoes', quantity: 4, unit: 'whole' },
      { name: 'fresh basil', quantity: 1, unit: 'handful' },
      { name: 'garlic', quantity: 2, unit: 'cloves' },
      { name: 'olive oil', quantity: 3, unit: 'tbsp' },
      { name: 'salt', quantity: 0.5, unit: 'tsp' },
      { name: 'black pepper', quantity: 0.25, unit: 'tsp' },
    ],
    steps: [
      'Dice tomatoes and combine with torn basil, 2 tbsp olive oil, salt and pepper. Set aside to macerate.',
      'Grill or toast bread slices until golden and charred in spots.',
      'Rub each slice immediately with a halved raw garlic clove.',
      'Drizzle with remaining olive oil, then pile the tomato mixture on top.',
      'Serve immediately.',
    ],
  },
];
